name: spending
description: A new Flutter project spending

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  sqflite: ^2.0.2+1
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_charts: ^19.1.54
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/



  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis-ExtraLight.ttf
